### ISSUE TITLE
Android Search - Caching

### ISSUE THREAD

**Issue by loc8malta** [loc8malta/Home#10]
Android, Web,caching search results

**Comment by gaucidaniel** [comment]
Fixed

**Comment by rodneygreenpops** [comment]
- Create a wrapper with firebase queue on console server. requests/response

**Comment by zammitjames** [comment]
-> Make sure textfield contains text and is not empty
-> Push {"search_text": actualSearchText} to "queue/search/listings/requests"
-> Get the Key of the data you saved to requests
-> Create on.("value") event listener to wait for reply on "queue/search/listings/response/$key"
-> Initial value may be null till the server creates the response (cater for with if snapshot != null)
-> when the response is not null remove the observer and the value at the given path (after passing locally through your datasource)
-> enjoy life

**Comment by zammitjames** [comment]
feel free to go over the server code if you think somethings wrong:

https://gist.github.com/zammitjames/c56b713bc6fe095e92c1b96d9d656f5b

**Comment by gaucidaniel** [comment]
Fixed (v1.0 build 29)
