### ISSUE TITLE
Voucher Redeemed/Expired Incorrect

### ISSUE THREAD

**Issue by loc8malta** [loc8malta/Home#15]
For some reason, the voucher is sometimes being shown as expired or redeemed when it says "One month from now" or I would not have redeemed the voucher.

**Comment by gaucidaniel** [comment]
Is this with regards to the "Free track day" voucher? I issued that voucher with 0 uses by mistake, and as such it cannot be used.

**Comment by zammitjames** [comment]
How about we use -1 to issue unlimited vouchers?

**Comment by gaucidaniel** [comment]
So that way the default would be -1 (handled by the clients and shown as Unlimited), but can be changed to any number of uses larger than 0?

**Comment by zammitjames** [comment]
cool bro

**Comment by gaucidaniel** [comment]
Handled from the Android side, will update Web version to reflect these changes. (Android v1.0 build 27)
