### ISSUE TITLE
We - Forgot Password - Mouse Hover

### ISSUE THREAD

**Issue by zammitjames** [loc8malta/Home#29]
- When hovering the mouse on it change the cursor icon to show that its clickable.

**Comment by zammitjames** [comment]
On mac, it seems to be working just fine, on windows however its not showing. Tried Chrome, Internet Explorer and Firefox.

**Comment by gaucidaniel** [comment]
I tested this on windows on Chrome, Edge and Firefox and it seemed to be working correctly, on which Windows version was this?
