### ISSUE TITLE
Take me there on Web

### ISSUE THREAD

**Issue by zammitjames** [loc8malta/Home#30]
Add Overlay on the map view OR a button "Take me there" under the map view which redirects to googles maps with a pointer.

Example below:
https://www.google.com/maps/place/27°59'16.4%22N+86°55'31.1%22E/@27.9879012,86.9231254,809m/data=!3m2!1e3!4b1!4m5!3m4!1s0x0:0x0!8m2!3d27.9879012!4d86.9253141

**Comment by gaucidaniel** [comment]
Added feature
